name: Script Injection

on:
  workflow_dispatch:
    inputs:
      name:
        type: text
        default: Elvis
  


jobs:

  job1:
    
    runs-on: ubuntu-latest

    
    steps:
      # Runs a single command using the runners shell
      - name: Show Script Injection
        run: |
          test="${{github.event.inputs.name}}"
          echo "This should be fun"
          echo $test
          
      - name: Stop Script Injection
        env:
          TEST: ${{github.event.inputs.name}}
        run: |
          echo "This should be fun"
          echo $TEST
          
      

      
